export const flats = [
  {
    id: 13,
    name: "ბინა 13",
    area: 100,
    balcony: 12,
    living: 65,
    bedroom: "სტუდიო",
    image: "/flats/house-49-3d.webp",
  },
  {
    id: 15,
    name: "ბინა 15",
    area: 100,
    balcony: 10,
    living: 70,
    bedroom: "2 საძინებელი",
    image: "/flats/house-50-3d.webp",
  },
  {
    id: 17,
    name: "ბინა 17",
    area: 85,
    balcony: 8,
    living: 58,
    bedroom: "1 საძინებელი",
    image: "/flats/house-49-3d.webp",
  },
  {
    id: 19,
    name: "ბინა 19",
    area: 120,
    balcony: 15,
    living: 80,
    bedroom: "3 საძინებელი",
    image: "/flats/house-51-3d.webp",
  },
  {
    id: 21,
    name: "ბინა 21",
    area: 95,
    balcony: 11,
    living: 62,
    bedroom: "სტუდიო",
    image: "/flats/house-52-3d.webp",
  },
  {
    id: 23,
    name: "ბინა 23",
    area: 110,
    balcony: 13,
    living: 75,
    bedroom: "2 საძინებელი",
    image: "/flats/house-51-3d.webp",
  },
  {
    id: 24,
    name: "ბინა 23",
    area: 110,
    balcony: 13,
    living: 75,
    bedroom: "2 საძინებელი",
    image: "/flats/house-53-3d.webp",
  },
  {
    id: 25,
    name: "ბინა 23",
    area: 110,
    balcony: 13,
    living: 75,
    bedroom: "2 საძინებელი",
    image: "/flats/house-52-3d.webp",
  },
  {
    id: 26,
    name: "ბინა 23",
    area: 110,
    balcony: 13,
    living: 75,
    bedroom: "2 საძინებელი",
    image: "/flats/house-54-3d.webp",
  },
  {
    id: 27,
    name: "ბინა 23",
    area: 110,
    balcony: 13,
    living: 75,
    bedroom: "2 საძინებელი",
    image: "/flats/house-55-3d.webp",
  },
];
